FROM debian:stable-slim

# install ca-certificates so that HTTPS works consistently
# other runtime dependencies for Python are installed later
RUN apt-get update && \
	apt-get install -y \
	ca-certificates \
    dnsutils \
    curl \
    jq \
    git \
    mariadb-client \
    postgresql-client \
    vim \
  && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
